//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class TTask
    {
        public int ID { get; set; }
        public string TextOfTask { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> CreatorID { get; set; }
        public Nullable<int> LastEditorID { get; set; }
        public Nullable<System.DateTime> LastEditedDate { get; set; }
        public string Users { get; set; }
        public string NameOfTask { get; set; }

        public void AddNewUser(int UserID)
        {
            if (Users == null || String.IsNullOrEmpty(Users))
                Users = UserID.ToString();
            else
                Users += "," + UserID.ToString();
        }
    }
}
